typography_spectrum: 0.3968851
color:
  saturation: 0.6685740717221051
  brandStrength: 0.003515537828207016
  lightness: 0.4694294717628509
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  rhythmicContrast: 0.3352355903480202
layout_spectrum: 0.8314193184487522
author:
  name: Patrick Danber
  email: patrick@patrickdanber.com
name: Patrick Danber
navigation:
  - name: about
    id: 5c0df68f-629b-49a2-826e-754ee431f19d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/543d0879-dfde-4867-a3b1-9ab0aff90da6.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: How I make me.
