author:
  name: Patrick Danber
  email: patrick@patrickdanber.com
title: How I make me.
name: Patrick Danber
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8748657
  brandStrength: 0.4005274320952594
  lightness: 0.2874517
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  rhythmicContrast: 0.1906552
typography_spectrum: 0.06928033
layout_spectrum: 0.7975295
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/543d0879-dfde-4867-a3b1-9ab0aff90da6.ico
