author:
  name: Patrick Danber
  email: patrick@patrickdanber.com
title: How I make me.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.07894735
  lightness: 0.4602578
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  rhythmicContrast: 0.8632861
typography_spectrum: 0.3968851
layout_spectrum: 0.8314193184487522
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/543d0879-dfde-4867-a3b1-9ab0aff90da6.ico
name: Patrick Danber
