author:
  name: Patrick Danber
  email: patrick@patrickdanber.com
title: How I make me.
name: Patrick Danber
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.796098206192255
  lightness: 0
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  rhythmicContrast: 1
typography_spectrum: 0.5290011
layout_spectrum: 1
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/543d0879-dfde-4867-a3b1-9ab0aff90da6.ico
